title: Nathan Rosen # your name (or website title) here
logo: "/images/6FB5FD7F-9E42-4F5C-BE04-D13CF10E6667.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href=https://www.linkedin.com/in/nathan-rosen-481978210/
   <a href="/pdf/September 21 Current Resume 2021.pdf" class="btn btn--info">Resume</a>  
  <br>
 
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://github.com/natanzrosen/">GitHub</a>  
  <br>
 
  
theme: jekyll-theme-minimal
